### ISSUE TITLE
please add consistent data and code links for all chart templates

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/highcharts-line-annotated#1]
It would be great if we had consistent data and code links for all of the Chart.js templates and Highchart template on GitHub.

Currently they say “Download dataset [link] powering this visualization”

My preference is to do something more similar to our Leaflet templates, where we say:

“View data and code” [repo link], created by HandsOnDataviz [book link] with Chart.js (or Highcharts) [link]

Let me know what you think…

**Comment by ilyankou** [comment]
All templates should now have the format you suggested.
